pillar.example, rabbitmq/init.sls
Ability to request a specific version via the pillar added.
=> Added basic versioning support

rabbitmq/init.sls
I am sorry, my last attempt did not push the right version!
=> clean patch

rabbitmq/config.sls, rabbitmq/config_bindings.sls, rabbitmq/config_exchange.sls, rabbitmq/config_queue.sls
=> Replace deprecated iteritems() with items()

FORMULA
This allows users to create their own package for use with SPM
(See https://github.com/saltstack-formulas/nginx-formula/blob/master/FORMULA for example)
=> Adding formula for SPM

.travis.yml, kitchen.yml, rabbitmq/latest.sls
---
No.
* Automated using https://github.com/myii/ssf-formula/pull/99
* https://github.com/saltstack-formulas/rabbitmq-formula/pull/53#issuecomment-553480289
Add a suite to test `.latest`, to follow up #53 (CC: @sylvainfaivre @daks).  Still passes through the `default` verifier.  Available for all platforms but only enabled for `debian-10` in Travis.
UPDATE: Had to add another commit (89b470f7124795353a5087ac872d1e8c510f240c) to ensure that `python-apt` or `python3-apt` is installed beforehand.  These are the platforms that are working currently:
* https://travis-ci.org/myii/rabbitmq-formula/builds/613098952
Existing.
As seen in Travis.
=> ci(kitchen+travis): add `latest` suite

pillar.example, rabbitmq/config.sls, test/integration/default/controls/rabbitmq_users_spec.rb
---
No.
https://github.com/saltstack-formulas/rabbitmq-formula/pull/51
Remove RabbitMQ guest user by default, but allow to keep it.
This is similar to https://github.com/saltstack-formulas/rabbitmq-formula/pull/51
But, as I replied in that PR :
> The default guest user has specific settings : il can only connect from localhost, and it has full access to the / virtual host.
> If I were to recreate it with a rabbitmq:user pillar, I wouldn't know how to do it.
> For this reason, I think the more practical way is what @daks proposed : have a pillar remove_guest_user, set to True by default but that a user can set to False if needed (for dev env) for example.
`remove_guest_user` in `pillar.example` (defaults to `true`)
=> feat(config.sls): remove guest user by default

kitchen.yml, pillar.example, rabbitmq/config.sls, rabbitmq/files/rabbitmq-env.conf, test/integration/default/controls/config.rb, test/salt/states/files/init.sls
---
This PR adds support to manage a file to provide to RabbitMQ environment variables. Those are mandatory to change some core settings, like the DB location. See https://www.rabbitmq.com/relocate.html and https://www.rabbitmq.com/configure.html
No.
In  `config.sls` I added the management of `/etc/rabbitmq/rabbitmq-env.conf` file. It can be populated using pillar `rabbitmq:env`.
Please see `pillar.example`.
=> Management of env file

rabbitmq/config.sls, rabbitmq/config_files.sls
---
No.
* https://github.com/saltstack-formulas/salt-formula/issues/452
* https://github.com/saltstack-formulas/salt-formula/pull/451
As described in the related issue and PR above.
This is the error encountered here:
* https://travis-ci.org/myii/rabbitmq-formula/jobs/651200625#L1830
* https://travis-ci.org/myii/rabbitmq-formula/jobs/651200626#L1779
As-is.
As shown in Travis.
=> fix(slspath): use `tplroot` to prevent path errors in `Neon`

rabbitmq/package-map.jinja
=> feat(suse): basic suse support

CODEOWNERS, kitchen.yml, rabbitmq/_mapdata/_mapdata.jinja, rabbitmq/_mapdata/init.sls, test/integration/default/controls/_mapdata_spec.rb, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-30.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/share/README.md, test/integration/share/inspec.yml, test/integration/share/libraries/system.rb
---
No.
* Automated using https://github.com/myii/ssf-formula/pull/282
=> test(map): verify `map.jinja` dump using `_mapdata` state

rabbitmq/_mapdata/_mapdata.jinja, rabbitmq/_mapdata/init.sls, test/integration/default/controls/_mapdata_spec.rb, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-30.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/284
=> refactor(map): use top-level `values:` key in `map.jinja` dumps

rabbitmq/_mapdata/init.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-30.yaml, test/integration/default/files/_mapdata/fedora-31.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/287
=> fix(_mapdata): ensure map data is directly under `values`

rabbitmq/latest.sls
---
No.
Bintray is shutting down on May 1st, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
The RabbitMQ team now provides packages on other services, as advised in https://www.rabbitmq.com/install-debian.html
=> fix(latest.sls): change apt repository following bintray shutdown

rabbitmq/config/user/install.sls, rabbitmq/package/install.sls, rabbitmq/parameters/defaults.yaml, rabbitmq/parameters/os_family/Debian.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
---
No.
Fix bug:
```
Function: rabbitmq_user.present
Result: False
Comment: Error: RabbitMQ command failed: Error:
{:undef, [{:rabbit_auth_backend_internal, :check_user_login, ["rabbitmq-config-user-present-airflow", [password: "password"]], []}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 680]}, {:erl_eval, :exprs, 2, []}]}
Started: 16:09:55.796041
Duration: 2056.719 ms
```
Set systemd to 100 secs.
=> fix(user): fix rendering error for user; fix ci

rabbitmq/package/install.sls
---
No.
Goes with my previous PR, removes old repo which now generate a warning message
=> fix(install.sls): remove old apt repository following bintray shutdown

docs/README.rst, kitchen.yml, rabbitmq/config/plugin/clean.sls, rabbitmq/config/policy/clean.sls, rabbitmq/config/queue/clean.sls, rabbitmq/config/upstream/clean.sls, rabbitmq/config/user/clean.sls, rabbitmq/config/vhost/clean.sls, rabbitmq/service/clean.sls, test/integration/default/controls/services.rb
---
No.
The use of requisites is unnecessary for most rabbitmq **config/*/clean** states., and can cause state failures in `rabbitmq`  executing under same high state as  `rabbitmq.clean` .
=> chore(clean): remove requires from config clean states

rabbitmq/config/cluster/install.sls
=> fix(cluster): corrected user/group

pillar.example, rabbitmq/config/file/install.sls, rabbitmq/files/default/config.tmpl, test/integration/default/files/_mapdata/amazonlinux-2.yaml, test/integration/default/files/_mapdata/arch-base-latest.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/gentoo-2-sysd.yaml, test/integration/default/files/_mapdata/gentoo-2-sysv.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/oraclelinux-7.yaml, test/integration/default/files/_mapdata/oraclelinux-8.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
---
No.
This PR fixes a bug.
The formula generates corrupted `rabbitmq.conf` if a custom configuration is supplied.  
The corruption is caused by using the Jinja2 **upper** filter in the `config.tmpl` file. 
RabbitMQ configuration directives should be lowercase per https://www.rabbitmq.com/configure.html#config-file and/or not modified from what is supplied in pillar data.
=> fix(config): formula creates corrupt config file

.gitlab-ci.yml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/salt/states/files/init.sls
=> ci(centos,suse): get ci working

rabbitmq/config/users/install.sls
---
No.
#84 
The guest user is deleted from the default node (rabbit@localhost).  
This PR adds multinode support for this delete-guest feature
=> fix(guest): remove guest user from all nodes

pillar.example, rabbitmq/config/files/install.sls, rabbitmq/config/plugins/install.sls, rabbitmq/files/default/systemd.ini.jinja, rabbitmq/package/install.sls, rabbitmq/parameters/defaults.yaml, rabbitmq/parameters/os_family/Debian.yaml, rabbitmq/service/clean.sls, rabbitmq/service/running.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> fix(service): ensure services use config files

docs/README.rst, pillar.example, rabbitmq/config/clusters/clean.sls, rabbitmq/config/clusters/install.sls, rabbitmq/config/files/clean.sls, rabbitmq/config/files/install.sls, rabbitmq/config/users/clean.sls, rabbitmq/config/users/install.sls, rabbitmq/parameters/defaults.yaml, rabbitmq/service/running.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> fix(cluster): fix some issues clustering multinode

rabbitmq/config/bindings/clean.sls, rabbitmq/config/clusters/clean.sls, rabbitmq/config/exchanges/clean.sls, rabbitmq/config/plugins/clean.sls, rabbitmq/config/policies/clean.sls, rabbitmq/config/queues/clean.sls, rabbitmq/config/users/clean.sls, rabbitmq/config/vhosts/clean.sls
=> chore(clean): stop noise if /var/lib/rabbitmq missing

rabbitmq/service/running.sls
---
No.
If root does not own service file in /usr/lib/systemd/system then systemctl enable fails.
=> fix(service): root must own systemd file

rabbitmq/config/files/install.sls, rabbitmq/config/users/clean.sls, rabbitmq/config/users/install.sls, rabbitmq/parameters/defaults.yaml, test/integration/nopillars/files/_mapdata/centos-7.yaml
=> fix(jinja2): use defaults if node pillar data incomplete

rabbitmq/config/clusters/install.sls
=> fix(clusters): remove multinode requisite = rendering error

pillar.example, rabbitmq/config/clusters/clean.sls, rabbitmq/config/clusters/install.sls, rabbitmq/config/files/clean.sls, rabbitmq/config/files/install.sls, rabbitmq/files/default/systemd.ini.jinja, rabbitmq/parameters/defaults.yaml, rabbitmq/service/clean.sls, rabbitmq/service/running.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml, test/integration/nopillars/files/_mapdata/centos-7.yaml
=> fix(service): set correct mnesia_dir and fix join cluster

pillar.example, rabbitmq/config/policies/install.sls, rabbitmq/config/upstreams/install.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> fix(upstream): use specificed name for the upstream

pillar.example, rabbitmq/config/policies/install.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
---
No.
Passing JSON string via list is too hard to get working consistently. 
It is sometimes not possible to fix "Too many functions declared in state ..." errors
=> refactor(policies): use dict to avoid 'too many functions' issues

rabbitmq/config/clusters/clean.sls
=> fix(cluster): fix clean state

pillar.example, rabbitmq/config/queues/install.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> fix(queues): apply queue arguments if specified

pillar.example, rabbitmq/config/exchanges/install.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> fix(exchanges): accept arguments if supplied

rabbitmq/config/bindings/clean.sls, rabbitmq/config/bindings/install.sls, rabbitmq/config/exchanges/clean.sls, rabbitmq/config/exchanges/install.sls, rabbitmq/config/plugins/install.sls, rabbitmq/config/queues/clean.sls, rabbitmq/config/queues/install.sls, rabbitmq/files/default/systemd.ini.jinja
=> fix(formula): fix exchanges and bindings

pillar.example, rabbitmq/config/parameters/clean.sls, rabbitmq/config/policies/clean.sls, rabbitmq/config/policies/install.sls, rabbitmq/config/queues/clean.sls, rabbitmq/config/users/clean.sls, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> chore(policy): support definition as yaml

rabbitmq/config/clean.sls, rabbitmq/config/clusters/clean.sls, rabbitmq/config/init.sls, rabbitmq/config/queues/clean.sls, rabbitmq/config/queues/install.sls, rabbitmq/config/users/install.sls
=> refactor(cluster): simplify cluster.clean and reorder config.init

.gitlab-ci.yml, pillar.example, rabbitmq/config/parameters/install.sls, test/integration/default/files/_mapdata/almalinux-8.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-10.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/fedora-33.yaml, test/integration/default/files/_mapdata/fedora-34.yaml, test/integration/default/files/_mapdata/opensuse-15.yaml, test/integration/default/files/_mapdata/opensuse-tumbleweed.yaml, test/integration/default/files/_mapdata/oraclelinux-7.yaml, test/integration/default/files/_mapdata/oraclelinux-8.yaml, test/integration/default/files/_mapdata/rockylinux-8.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> feat(federation-set): add support for

.gitlab-ci.yml, rabbitmq/config/init.sls, test/integration/default/files/_mapdata/almalinux-8.yaml, test/integration/default/files/_mapdata/centos-7.yaml, test/integration/default/files/_mapdata/centos-8.yaml, test/integration/default/files/_mapdata/debian-11.yaml, test/integration/default/files/_mapdata/debian-9.yaml, test/integration/default/files/_mapdata/fedora-32.yaml, test/integration/default/files/_mapdata/oraclelinux-7.yaml, test/integration/default/files/_mapdata/oraclelinux-8.yaml, test/integration/default/files/_mapdata/rockylinux-8.yaml, test/integration/default/files/_mapdata/ubuntu-16.yaml, test/integration/default/files/_mapdata/ubuntu-18.yaml, test/integration/default/files/_mapdata/ubuntu-20.yaml
=> ci(suite): fix and enable full ci again

rabbitmq/config/init.sls
=> fix(clustering): do clustering last

pillar.example
=> chore(pillar.example): add consumer timeout

rabbitmq/package/repo/install.sls
---
No.
Added a grain check to render out the correct URL in the case of AmazonLinux
=> fix(package/repo/install): Add AmazonLinux check, set canonical names for yum repos

rabbitmq/config/plugins/install.sls
---
No.
This PR uses 127.0.0.1 for local download as that is guaranteed to work.  I think hostesfile-formula is messing up "localhost" in /etc/hosts and breaking this, a reminder that 127.0.0.1 is fine here.
=> fix(robustness): use loopbackip instead of localhost

rabbitmq/files/default/systemd.ini.jinja
---
No.
This PR stops overwriting after/wants Unit parameters.
```
diff:
---
+++
@@ -1,8 +1,10 @@
-# systemd unit example
+#########################################################
+# File managed by Salt. Changes risk being overwritten.
+#########################################################
[Unit]
-Description=RabbitMQ broker
-After=network.target epmd@0.0.0.0.socket
-Wants=network.target epmd@0.0.0.0.socket
+Description=RabbitMQ broker
+Wants=network-online.target
+After=syslog.target network.target
```
=> fix(default): update systemd file with correct defaults

.pre-commit-config.yaml
---
No.
Fixes this error in the pre-commit : 
```
error in salt-lint setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.6.*'
```
=> chore: upgrade salt-lint release

.gitlab-ci.yml
---
No.
Disable CI for unsupported OS releases : 
- Debian 10, see https://www.rabbitmq.com/install-debian.html
- CentOS 7 and Oracle Linux 7, see https://www.rabbitmq.com/install-rpm.html
=> ci: disable unsupported OS releases

rabbitmq/package/repo/install.sls
---
No.
Replace the usage of `grains.osfullname` in `package.repo.install` because in newer Salt versions it may return an expanded value, breaking the package repositories.
In Salt 3006, "osfullname" grain may return a new, expanded value. 
From the ([changelog](https://docs.saltproject.io/en/master/topics/releases/3006.0.html)):
> Some Linux distributions (like AlmaLinux, Astra Linux, Debian, Mendel, Linux Mint, Pop!_OS, Rocky Linux) report different oscodename, osfullname, osfinger grains if lsb-release is installed or not. They have been changed to only derive these OS grains from /etc/os-release. [#61618](https://github.com/saltstack/salt/issues/61618)
Comparing the older and new versions:
```
salt-call grains.items --local on the server (3004.2):
os:
Debian
os_family:
Debian
osarch: …
```
=> fix: Replace usages of grains.osfullname in `package.repo.install`

.gitlab-ci.yml, test/integration/default/files/_mapdata/ubuntu-22.yaml
---
No.
fix Ubuntu 22.04 expected mapdata
=> ci: fix Ubuntu 22.04 expected mapdata
